import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {chromium} from 'playwright';import {serve} from '../scripts/server.mjs';import {root} from '../scripts/build.mjs';import {init,preview} from '../scripts/project.mjs';
const output=path.join(root,'artifacts');await fs.mkdir(output,{recursive:true});const host=await serve(root,{port:0});let browser,projectHost,tmp;const errors=[],checks=[];
try{
 browser=await chromium.launch({headless:true,args:['--enable-webgl',process.platform==='darwin'?'--use-angle=metal':'--use-angle=swiftshader']});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));
 await p.goto(host.url);await p.screenshot({path:path.join(output,'home.png'),fullPage:true});
 await p.goto(host.url+'/apps/effects/');await p.waitForFunction(()=>window.effectsLab?.ready);
 const effects=await p.evaluate(()=>{const a=window.effectsLab;return a.studies.map(s=>{a.select(s.id);a.seek(2.2);a.bypass(false);const before=a.png();a.bypass(true);const bypass=a.png();a.bypass(false);a.seek(1);a.seek(2.2);return {id:s.id,visible:before!==bypass,seekExact:before===a.png()}})});
 for(const e of effects){assert.ok(e.visible,e.id);assert.ok(e.seekExact,e.id)}checks.push({effects:effects.length});await p.screenshot({path:path.join(output,'effects.png')});
 await p.goto(host.url+'/apps/films/');await p.waitForFunction(()=>window.editableframe?.ready);
 const films=await p.evaluate(async()=>{const a=window.editableframe,result=[];for(const id of Object.keys(a.templates)){await a.select(id);await a.seek(2.2);const before=a.png(),ctx=document.querySelector('#screen').getContext('2d'),pixels=ctx.getImageData(0,0,1280,720).data;await a.seek(3.1);const changed=a.png()!==before;await a.seek(2.2);const after=ctx.getImageData(0,0,1280,720).data;let differing=0,total=0;for(let i=0;i<pixels.length;i+=4){let delta=0;for(let k=0;k<3;k++){const d=Math.abs(pixels[i+k]-after[i+k]);delta=Math.max(delta,d);total+=d;}if(delta) differing++;}result.push({id,changed,seekExact:before===a.png(),differingPixels:differing,meanChannelDelta:total/(1280*720*3),repeatable:differing/(1280*720)<.001&&total/(1280*720*3)<.02})}return result});await fs.writeFile(path.join(output,'film-checks.json'),JSON.stringify(films,null,2));for(const f of films){assert.ok(f.changed,f.id+' motion');assert.ok(f.repeatable,f.id+' repeated seek within documented antialias tolerance')}checks.push({films:films.length});await p.screenshot({path:path.join(output,'films.png')});
 await p.goto(host.url+'/apps/devices/');await p.waitForFunction(()=>window.library?.ready);const available=JSON.parse(await fs.readFile(path.join(root,'assets/devices/catalog.json'))).models.filter(x=>x.starter);
 for(const m of available){const loaded=await p.evaluate(async id=>{await window.library.select(id);return {id:window.library.current.id,hdr:window.library.inspectLighting().hdrSha256}},m.id);assert.equal(loaded.id,m.id);assert.ok(loaded.hdr)}checks.push({starterDevices:available.length});await p.evaluate(()=>window.library.select('craft-macbook-pro-16'));await p.screenshot({path:path.join(output,'devices.png')});
 tmp=await fs.mkdtemp(path.join(os.tmpdir(),'ef-browser-'));await init(path.join(tmp,'clip'));projectHost=await preview(path.join(tmp,'clip'),{port:0});await p.goto(projectHost.url);await p.waitForFunction(()=>window.editableframe?.ready);const history=await p.evaluate(async()=>{const a=window.editableframe;await a.seek(2);const canvas=document.querySelector('#screen'),ctx=canvas.getContext('2d'),pixels=()=>ctx.getImageData(0,0,canvas.width,canvas.height).data;const before=a.png(),bp=pixels();await a.edit({type:'set',clip:a.selected,anchor:'hero',property:'accent',value:'#ff8866'});const after=a.png(),ap=pixels();await a.undo();await a.seek(2);const up=pixels(),undoValue=a.studio.doc.clips[0].nodes[0].props.accent;await a.redo();await a.seek(2);const rp=pixels();function delta(x,y){let changed=0,total=0;for(let i=0;i<x.length;i+=4){let d=0;for(let k=0;k<3;k++){const v=Math.abs(x[i+k]-y[i+k]);total+=v;d=Math.max(d,v)}if(d)changed++}return{pixels:changed,mean:total/(canvas.width*canvas.height*3),pass:changed/(canvas.width*canvas.height)<.001&&total/(canvas.width*canvas.height*3)<.02}}return {changed:after!==before,undoValue,redoValue:a.studio.doc.clips[0].nodes[0].props.accent,undo:delta(bp,up),redo:delta(ap,rp)}});assert.ok(history.changed&&history.undo.pass&&history.redo.pass,JSON.stringify(history));assert.equal(history.undoValue,'#b9ef78');assert.equal(history.redoValue,'#ff8866');checks.push(history);
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'browser-results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));
}finally{await browser?.close();await projectHost?.close();await host.close();if(tmp)await fs.rm(tmp,{recursive:true,force:true})}
