import {Studio,clone,ticks} from '../../packages/core/index.mjs';import {effects,studies,templates,byId} from '../../packages/effects/catalog.mjs';import {createRenderer} from '../../packages/effects/renderer.mjs';import audit from './audit.json';import {binding} from './binding.mjs';
const $=s=>document.querySelector(s),renderer=createRenderer($('#screen'));let session=new Studio(templates,{binding,document:{version:1,clips:[],width:1280,height:720,fps:{num:24,den:1}}});session.doc.clips=studies.map(s=>session.make(s.id));session.check(session.doc);session.base=clone(session.doc);let selected=session.doc.clips[0].id,time=2.2,playing=false,bypass=false,last=0;
const clip=()=>session.clip(selected),spec=()=>templates[clip().template];function status(s){$('#status').textContent=s}function download(name,s){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function paint(){const c=clip(),info=renderer.draw(time,session.values(c,ticks(time)),c.payload.order,bypass);$('#seek').value=time;$('#clock').textContent=time.toFixed(2)+' / 6 s';$('#metrics').textContent=info.backend+' · '+info.passes+' passes · RGBA16F intermediates · '+info.requestedTimes.length+' source-time request(s)';return info;}
function execute(cmd,revision=session.revision,actor='user'){if(!['set','keyframes','panel','payload','batch'].includes(cmd.type))throw Error('This lab supports effect/property/panel edits only');const verify=c=>{if(c.type==='batch')c.commands.forEach(verify);else if(!['set','keyframes','panel','payload'].includes(c.type)||c.clip!==selected)throw Error('Proposal must target this clip');if(c.type==='panel')validatePanel(c.panel)};verify(cmd);const result=session.execute(cmd,revision,actor);playing=false;refresh();paint();return result;}
function change(anchor,property,value){return execute({type:'set',clip:selected,anchor,property,value,label:'Change '+property})}
function reorder(anchor,direction){const order=[...clip().payload.order],i=order.indexOf(anchor),j=i+direction;if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];return execute({type:'payload',clip:selected,payload:{order},label:'Reorder effects'})}
function panel(){return clip().panel||{groups:clip().nodes.map(n=>({title:n.label,fields:Object.keys(n.props).map(property=>({id:n.id+'.'+property,anchor:n.id,property,label:spec().schemas[n.type][property].label}))}))}}
function validatePanel(p){if(!Array.isArray(p?.groups))throw Error('Panel requires groups');for(const g of p.groups)for(const f of g.fields??[])if(f.kind||f.when)throw Error('This panel renderer supports direct typed fields only')}
function refresh(){const c=clip();$('#title').textContent=spec().title;$('#description').textContent=spec().description;$('#undo').disabled=!session.canUndo;$('#redo').disabled=!session.canRedo;$('#play').textContent=playing?'Pause':'Play';$('#stack').replaceChildren();for(const anchor of c.payload.order){const n=session.node(c,anchor),row=document.createElement('div');row.className='stack-item';const label=document.createElement('span');label.textContent=n.label;row.append(label);for(const [symbol,direction]of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.textContent=symbol;b.title='Move '+n.label+(direction<0?' earlier':' later');b.onclick=()=>reorder(anchor,direction);row.append(b)}$('#stack').append(row)}$('#controls').replaceChildren();for(const group of panel().groups){const section=document.createElement('section'),h=document.createElement('h3');h.textContent=group.title;section.append(h);for(const f of group.fields){const node=session.node(c,f.anchor),s=spec().schemas[node.type][f.property],row=document.createElement('label'),name=document.createElement('span'),out=document.createElement('output');name.textContent=f.label;row.append(name,out);const input=document.createElement(s.type==='enum'?'select':'input');if(s.type==='enum')for(const value of s.values)input.add(new Option(value,value));else input.type=s.type==='number'?'range':s.type==='color'?'color':s.type==='boolean'?'checkbox':'text';if(s.type==='number'){input.min=s.min;input.max=s.max;input.step=s.step??.01;out.textContent=node.props[f.property]}if(s.type==='boolean')input.checked=node.props[f.property];else input.value=node.props[f.property];input.dataset.anchor=f.anchor;input.dataset.property=f.property;input.onchange=()=>{try{change(f.anchor,f.property,s.type==='boolean'?input.checked:s.type==='number'?Number(input.value):input.value)}catch(e){status(e.message);refresh()}};row.append(input);section.append(row)}$('#controls').append(section)}$('#history').replaceChildren();session.history.slice(-8).forEach((e,i)=>{const li=document.createElement('li');li.textContent=(i+Math.max(0,session.history.length-8)<session.cursor?'● ':'○ ')+e.label+' · '+e.actor;$('#history').append(li)});$('#panel').value=JSON.stringify(panel(),null,2);document.querySelectorAll('.clip').forEach(b=>b.classList.toggle('active',b.dataset.id===c.template));}
function select(id){const c=session.doc.clips.find(c=>c.template===id||c.id===id);if(!c)throw Error('Unknown scene');selected=c.id;time=2.2;playing=false;bypass=false;$('#bypass').checked=false;refresh();paint();return true;}
function restore(raw){const s=Studio.restore(raw,templates,binding);if(s.doc.clips.length!==studies.length||new Set(s.doc.clips.map(c=>c.template)).size!==studies.length)throw Error('This lab requires its 30 study clips');for(const c of s.doc.clips){const t=templates[c.template];if(c.nodes.length!==t.nodes.length||c.nodes.some((n,i)=>n.id!==t.nodes[i].id||n.effect!==t.nodes[i].effect)||c.start!==0||c.rate!==1||c.sourceIn!==0)throw Error('Unsupported source or effect structure');if(c.panel)validatePanel(c.panel)}session=s;selected=s.doc.clips[0].id;select(selected)}
for(const s of studies){const button=document.createElement('button');button.className='clip';button.dataset.id=s.id;const title=document.createElement('b'),sub=document.createElement('small');title.textContent=s.title;sub.textContent=s.id.startsWith('look.')?'Composed look · '+s.stack.length+' effects':byId[s.stack[0].effect].category+' · limited prototype';button.append(title,sub);button.onclick=()=>select(s.id);$('#clips').append(button)}
$('#play').onclick=()=>{playing=!playing;last=performance.now();$('#play').textContent=playing?'Pause':'Play'};$('#seek').oninput=e=>{time=Number(e.target.value);playing=false;paint()};$('#bypass').onchange=e=>{bypass=e.target.checked;paint()};$('#undo').onclick=()=>{session.undo();playing=false;refresh();paint()};$('#redo').onclick=()=>{session.redo();playing=false;refresh();paint()};$('#save').onclick=()=>download('editableframe-effects.scene.json',session.serialize());$('#open').onchange=async e=>{try{restore(await e.target.files[0].text());status('Project and undo history restored')}catch(e){status(e.message)}};
$('#context').onclick=()=>download('effects-llm-context.json',JSON.stringify({revision:session.revision,capabilities:session.capabilities(selected),effectLimits:spec().stack.map(s=>({anchor:s.anchor,effect:s.effect,scope:byId[s.effect].limit})),example:{baseRevision:session.revision,command:{type:'set',clip:selected,anchor:clip().nodes[1].id,property:'enabled',value:false}}},null,2));$('#apply-proposal').onclick=()=>{try{const p=JSON.parse($('#proposal').value);execute(p.command,p.baseRevision,'model');status('Applied model proposal with tracked history')}catch(e){status(e.message)}};$('#apply-panel').onclick=()=>{try{execute({type:'panel',clip:selected,panel:JSON.parse($('#panel').value),label:'Replace control panel'});status('Panel changed; undo restores it')}catch(e){status(e.message)}};
$('#show-audit').onclick=()=>{playing=false;$('#studio').hidden=true;$('#audit').hidden=false};$('#show-studio').onclick=()=>{$('#studio').hidden=false;$('#audit').hidden=true};
for(const [id,g]of Object.entries(audit.groups)){const card=document.createElement('div');card.className='count';const n=document.createElement('strong'),l=document.createElement('span');n.textContent=audit.summary.groups[id];l.textContent=g.label;card.append(n,l);$('#counts').append(card);$('#group').add(new Option(g.label,id))}
function rows(){const query=$('#query').value.toLowerCase(),group=$('#group').value,demo=$('#demo-filter').value;const found=audit.effects.filter(e=>(group==='all'||e.group===group)&&(demo==='all'||(demo==='yes')===!!byId[e.id])&&(e.name+' '+e.category+' '+e.needs).toLowerCase().includes(query));$('#rows').replaceChildren();for(const e of found){const tr=document.createElement('tr');const texts=[e.name,e.route,e.needs+' '+e.risk,byId[e.id]?'Implemented prototype: '+byId[e.id].limit:'Implementation route assessed; not built here.'];for(let i=0;i<4;i++){const td=document.createElement('td');td.textContent=texts[i];if(i===0){const small=document.createElement('small');small.textContent=e.category+' · '+e.parameters+' visible controls';td.append(small)}if(i===3){const small=document.createElement('small');small.textContent=e.source.map(x=>x.path+':'+x.line).join(' / ');td.append(small)}tr.append(td)}$('#rows').append(tr)}$('#row-count').textContent=found.length+' effects shown · Classification is an engineering assessment, not measured Adobe parity.'}for(const id of ['query','group','demo-filter'])$('#'+id).oninput=rows;rows();
function loop(now){if(playing){time=(time+Math.min(.1,(now-last)/1000))%6;paint()}last=now;requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.effectsLab={ready:true,studies,effects,binding,get session(){return session},get selected(){return selected},select,seek(t){time=t;playing=false;return paint()},change,execute,reorder,undo(){session.undo();refresh();return paint()},redo(){session.redo();refresh();return paint()},bypass(v){bypass=v;$('#bypass').checked=v;return paint()},inspect:renderer.inspect,png:renderer.png,jpg:renderer.jpg,serialize:()=>session.serialize(),restore};select('look.aurora');if(location.search.includes('render=1'))document.body.classList.add('render');
