const n=(min,max,label,step=.05)=>({type:'number',min,max,label,step}),c=label=>({type:'color',label}),t=label=>({type:'text',label,maxLength:50}),b=label=>({type:'boolean',label});
const make=(id,title,duration,kind,creator,reference,description,props,schema)=>({id:'reference.'+id,title,duration,scene:id,family:'reference',category:'Reference studies',testTime:duration*.48,kind,creator,reference,description,nodes:[{id:id+'.direction',type:id,label:'Art direction',props,keys:{}}],schemas:{[id]:schema}});
export const studies=[
make('grain','Somewhere, slowly',16,'Textured film','@jurlycat',0,'A moving landscape inside a film window: field parallax, sunset, overhead wires and deterministic animated grain.',{sun:'#ef9d47',fields:'#60734d',grain:.36,speed:1,window:1},{sun:c('Sunset'),fields:c('Fields'),grain:n(0,.8,'Film grain',.01),speed:n(.3,1.8,'Landscape speed'),window:n(.75,1.2,'Window framing')}),
make('unet','A shape inside the noise',18,'Scientific explainer','@DotCSV',1,'A schematic denoising pass through a U-Net: noisy input, multiscale features, skip connections and predicted noise. Illustrated output; no neural inference.',{accent:'#73b7ff',noise:.85,skip:true,pulse:1,width:1},{accent:c('Signal color'),noise:n(.1,1,'Input noise'),skip:b('Show skip connections'),pulse:n(.4,1.8,'Signal travel speed'),width:n(.65,1.4,'Feature-stack depth')}),
make('dragon','The fossil takes flight',14,'Procedural 3D','@Stefan_3D_AI',2,'Original skeletal creature: articulated ribs, spine, jaw, wing fingers, talons and a segmented tail, with a slow specimen orbit.',{bone:'#d9c29c',wings:1,jaw:.35,speed:1,orbit:.4,explode:0},{bone:c('Bone material'),wings:n(.55,1.35,'Wing span'),jaw:n(0,1,'Jaw opening'),speed:n(.3,1.8,'Flight speed'),orbit:n(0,1.2,'Camera orbit'),explode:n(0,.8,'Skeleton separation')}),
make('paper','A small act of care',16,'Paper stop motion','@devteamdrew',3,'An original paper robot discovers a seed, waters it and shelters its first leaf. Pose holds, paper shadows and a page turn.',{body:'#d77847',leaf:'#648963',bounce:1,fps:12,grain:.2},{body:c('Character paper'),leaf:c('Leaf paper'),bounce:n(.4,1.5,'Acting amplitude'),fps:{...n(6,24,'Pose frames per second',1),integer:true},grain:n(0,.65,'Paper texture')}),
make('storybook','The light next door',16,'Cut-paper collage','@kevin_ngo',4,'An original night-time picture-book scene: paper windows, crayon stars, a child, a flying note and a distant light answering.',{sky:'#182b59',light:'#f4c777',stars:42,wind:1,grain:.22},{sky:c('Night paper'),light:c('Window glow'),stars:{...n(10,100,'Stars',1),integer:true},wind:n(.3,1.8,'Paper motion'),grain:n(0,.65,'Crayon texture',.01)}),
make('ink','From mark to message',16,'Ink animation','@shfred0',5,'An original visual metaphor: a drawn mark grows into a network, then a terminal and a message. Not a factual model biography.',{ink:'#f0e8d7',paper:'#151611',roughness:.65,tempo:1,stroke:2.2},{ink:c('Ink'),paper:c('Paper'),roughness:n(0,1.5,'Line boil'),tempo:n(.4,1.5,'Story pace'),stroke:n(1,5,'Pen width')}),
make('castle','A kingdom in miniature',14,'Procedural 3D','@chaseleantj',6,'A code-built limestone castle with battlements, an arched gateway, tiled roofs, bridge, trees, water and moving pennants.',{stone:'#d0ba98',roof:'#5b6873',height:1,orbit:.6,trees:36},{stone:c('Limestone'),roof:c('Roof tiles'),height:n(.7,1.4,'Tower height'),orbit:n(0,1.2,'Camera orbit'),trees:{...n(0,60,'Trees',1),integer:true}}),
make('warehouse','One parcel, many handoffs',16,'Isometric system','@_iyart_',7,'A parcel crosses a conveyor, scanner and gantry before joining dispatch. Every object is drawn in code using a shared isometric projection.',{parcel:'#bcf06b',belt:1,crane:1,packages:8,zoom:1},{parcel:c('Tracked parcel'),belt:n(.4,1.5,'Conveyor speed'),crane:n(.3,1.4,'Gantry travel'),packages:{...n(3,14,'Background parcels',1),integer:true},zoom:n(.8,1.2,'Camera framing')}),
make('underwater','The last blue train',18,'Cinematic 3D','@aniketjart',8,'An original brass observation train moves along an elevated underwater railway. Coral, fish, bubbles, fog and light shafts create depth.',{water:'#075f77',brass:'#c69a52',speed:1,fish:28,orbit:.45},{water:c('Water'),brass:c('Train brass'),speed:n(.3,1.6,'Train speed'),fish:{...n(0,60,'Fish count',1),integer:true},orbit:n(0,1,'Camera travel')}),
make('showreel','Make it move',15,'Kinetic showreel','@shneural · prompt study',null,'An original response to the shared 15-second showreel brief: elastic type, radial forms, depth tunnel and a particle-resolved end card.',{accent:'#d5ff63',secondary:'#a89eff',word:'MAKE IT MOVE',energy:1,bpm:120},{accent:c('Primary color'),secondary:c('Secondary color'),word:t('Final title'),energy:n(.4,1.5,'Motion energy'),bpm:{...n(80,160,'Beat grid · BPM',1),integer:true}}),
make('evolution','An idea learns to move',15,'Evolution promo','@AniSri016 · brief only',null,'A fictional product evolves from a single mark into a connected system and a spatial interface. Based on the requested brief; that account’s original clip is not verified.',{brand:'PARALLAX',accent:'#fa8255',ink:'#ece9df',pace:1,spread:1},{brand:t('Fictional brand'),accent:c('Brand accent'),ink:c('Lettering'),pace:n(.6,1.3,'Reveal pace'),spread:n(.6,1.4,'Network spread')})
];
export const templates=Object.fromEntries(studies.map(s=>[s.id,s]));
