// Renderer-independent authoring, source clocks, and reversible structural commands.
export const HZ=120000, ticks=s=>Math.round(s*HZ), seconds=t=>t/HZ;
export const clone=v=>structuredClone(v);
export const canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
export const uid=()=>crypto.randomUUID();
const fail=m=>{throw Error(m)};
const safe=k=>typeof k==='string'&&k.length>0&&k.length<180&&!['__proto__','constructor','prototype'].includes(k);
// Applications can register new typed values and interpolation without changing this core.
const valueTypes=new Map();
export function registerValueType(name,spec){if(!safe(name)||valueTypes.has(name)||typeof spec.validate!=='function')fail('Invalid or duplicate value type');valueTypes.set(name,spec);}
registerValueType('number',{validate:(v,s)=>Number.isFinite(v)&&(s.min===undefined||v>=s.min)&&(s.max===undefined||v<=s.max)&&(!s.integer||Number.isInteger(v)),interpolate:(a,b,u)=>a+(b-a)*u});
registerValueType('color',{validate:v=>typeof v==='string'&&/^#[\da-f]{6}([\da-f]{2})?$/i.test(v)});
registerValueType('text',{validate:(v,s)=>typeof v==='string'&&v.length<=(s.maxLength??160)});
registerValueType('enum',{validate:(v,s)=>s.values.includes(v)});
registerValueType('boolean',{validate:v=>typeof v==='boolean'});
registerValueType('json',{validate:v=>v!==undefined&&JSON.stringify(v)!==undefined});
export function validate(v,s){if(!s)fail('Unknown capability');const type=valueTypes.get(s.type);if(!type)fail('Missing value-type plugin: '+s.type);if(!type.validate(v,s))fail('Value outside declared capability: '+s.type);}
export const overlaySchema={text:{type:'text',maxLength:90,label:'Text'},x:{type:'number',min:0,max:1920,unit:'px',label:'Horizontal position'},y:{type:'number',min:0,max:1080,unit:'px',label:'Vertical position'},size:{type:'number',min:14,max:240,unit:'px',label:'Type size'},color:{type:'color',label:'Text color'},background:{type:'color',label:'Card color'},opacity:{type:'number',min:0,max:1,label:'Opacity'},visible:{type:'boolean',label:'Visible'},start:{type:'number',min:0,max:120,unit:'s',label:'Appears at'},end:{type:'number',min:0,max:120,unit:'s',label:'Disappears at'},style:{type:'enum',values:['card','plain','pill'],label:'Treatment'}};
export function descriptor(s,key){return {...s,label:s.label??key,unit:s.unit??(/angle|pitch|yaw|roll|bearing|azimuth|elevation/i.test(key)?'°':''),keyframe:s.keyframe??(!!valueTypes.get(s.type)?.interpolate&&!s.integer),impact:s.impact??['source'],owner:'scene'};}
export function sampleKeys(keys,t,base,schema={type:'number'}){if(!keys?.length)return base;if(t<=keys[0].time)return keys[0].value;for(let i=1;i<keys.length;i++){const a=keys[i-1],b=keys[i];if(t===b.time)return b.value;if(t<b.time){let u=(t-a.time)/(b.time-a.time);if(a.easing==='hold')u=0;else if(a.easing==='smooth')u=u*u*(3-2*u);const blend=valueTypes.get(schema.type)?.interpolate;return blend?blend(a.value,b.value,u):a.value;}}return keys.at(-1).value;}
export function sourceTime(clip,projectTick){return Math.max(0,Math.min(clip.sourceDuration-1,clip.sourceIn+Math.round((projectTick-clip.start)*clip.rate)));}
export const frameTime=(frame,fps={num:30,den:1})=>Math.round(frame*HZ*fps.den/fps.num);
export class Studio {
 constructor(templates,{document,binding='studio-v1',limit=8*1024*1024,budgets={}}={}){this.budgets={clips:1000,anchors:500,keys:1000,panelFields:200,panelGroups:20,commands:100,...budgets};this.templates=templates;this.binding=binding;this.limit=limit;this.seq=0;this.sid=uid();this.history=[];this.cursor=0;this.bytes=0;this.doc=document??{version:1,clips:[],fps:{num:30,den:1},width:1920,height:1080};this.check(this.doc);this.base=clone(this.doc);}
 get revision(){return this.sid+':'+this.seq} get canUndo(){return this.cursor>0}get canRedo(){return this.cursor<this.history.length}
 clip(id,doc=this.doc){return doc.clips.find(c=>c.id===id)??fail('Unknown clip')}
 schema(clip,node){return node.overlay?overlaySchema:this.templates[clip.template].schemas[node.type]}
 node(clip,id){return clip.nodes.find(n=>n.id===id)??fail('Unknown anchor')}
 values(clip,t){const local=sourceTime(clip,t)/HZ;return clip.nodes.map(n=>({...n,props:Object.fromEntries(Object.entries(n.props).map(([k,v])=>[k,sampleKeys(n.keys?.[k],local,v,this.schema(clip,n)[k])]))}));}
 capabilities(id){const c=this.clip(id);return {binding:this.binding,baseRevision:this.revision,clip:id,anchors:c.nodes.map(n=>({id:n.id,label:n.label,properties:Object.fromEntries(Object.entries(this.schema(c,n)).map(([k,s])=>[k,descriptor(s,k)])),values:n.props})),panel:c.panel};}
 make(template,start=0){const t=this.templates[template];if(!t)fail('Unknown template');return {id:uid(),template,name:t.title,start,duration:ticks(t.duration),sourceDuration:ticks(t.duration),sourceIn:0,rate:1,transform:{x:0,y:0,scale:1,opacity:1},nodes:clone(t.nodes),panel:clone(t.panel??null),html:clone(t.html??null),payload:clone(t.payload??null)};}
 check(doc){if(!Number.isSafeInteger(doc.width)||doc.width<1||doc.width>16384||!Number.isSafeInteger(doc.height)||doc.height<1||doc.height>16384||!Number.isSafeInteger(doc.fps?.num)||doc.fps.num<1||!Number.isSafeInteger(doc.fps?.den)||doc.fps.den<1)fail('Invalid canvas or frame rate');if(doc.version!==1||!Array.isArray(doc.clips)||doc.clips.length>this.budgets.clips)fail('Invalid project');const ids=new Set();for(const c of doc.clips){if(!this.templates[c.template])fail('Missing template adapter '+c.template+'; saved project preserved');if(!safe(c.id)||ids.has(c.id))fail('Invalid clip identity');ids.add(c.id);for(const k of ['start','duration','sourceDuration','sourceIn'])if(!Number.isSafeInteger(c[k])||c[k]<0)fail('Invalid clock');if(c.duration<1||c.sourceDuration<1||!Number.isFinite(c.rate)||c.rate<.1||c.rate>8)fail('Invalid duration or rate');if(c.sourceIn+Math.ceil(c.duration*c.rate)>c.sourceDuration+1)fail('Source range exceeded');if(!c.transform||!Number.isFinite(c.transform.x)||!Number.isFinite(c.transform.y)||!Number.isFinite(c.transform.scale)||!Number.isFinite(c.transform.opacity)||c.transform.scale<.1||c.transform.scale>3||c.transform.opacity<0||c.transform.opacity>1)fail('Invalid transform');const anchors=new Set();if(!Array.isArray(c.nodes)||c.nodes.length>this.budgets.anchors)fail('Invalid nodes');for(const n of c.nodes){if(!safe(n.id)||anchors.has(n.id))fail('Duplicate anchor');anchors.add(n.id);const schema=this.schema(c,n);if(!schema)fail('Unknown node type');if(Object.keys(n.props).length!==Object.keys(schema).length)fail('Missing capability values');for(const [k,v]of Object.entries(n.props))validate(v,schema[k]);for(const [k,keys]of Object.entries(n.keys??{})){if(!descriptor(schema[k],k).keyframe||keys.length>this.budgets.keys)fail('Property cannot be animated');let last=-1;for(const key of keys){validate(key.value,schema[k]);if(!Number.isFinite(key.time)||key.time<0||key.time<=last||key.time>c.sourceDuration/HZ||!['linear','smooth','hold'].includes(key.easing))fail('Invalid animation track');last=key.time;}}}for(const required of this.templates[c.template].nodes)if(!anchors.has(required.id))fail('Required renderer anchor missing');if(this.templates[c.template].validatePayload)this.templates[c.template].validatePayload(c.payload);if(c.panel)this.validatePanel(c,c.panel);if(c.html&&new TextEncoder().encode(JSON.stringify(c.html)).length>2*1024*1024)fail('HTML exceeds 2 MiB');}return doc;}
 validatePanel(c,p){if(!Array.isArray(p.groups)||p.groups.length>this.budgets.panelGroups)fail('Invalid panel');let count=0;const ids=new Set();const capability=f=>this.schema(c,this.node(c,f.anchor))[f.property]??fail('Panel binding unsupported');for(const g of p.groups){if(typeof g.title!=='string'||!Array.isArray(g.fields))fail('Invalid group');for(const f of g.fields){if(++count>this.budgets.panelFields||!safe(f.id)||ids.has(f.id))fail('Invalid field identity');ids.add(f.id);if(typeof f.label!=='string'||f.label.length>100)fail('Invalid field label');if(f.when)validate(f.when.equals,capability(f.when));if(f.kind==='macro'){if(!Number.isFinite(f.min)||!Number.isFinite(f.max)||f.max<=f.min||!f.mappings?.length)fail('Invalid macro');for(const m of f.mappings){const s=capability(m);if(s.type!=='number')fail('Macro requires numeric capabilities');validate(m.from,s);validate(m.to,s);}}else if(f.kind==='preset'){if(!f.operations?.length)fail('Empty preset');for(const o of f.operations)validate(o.value,capability(o));}else capability(f);}}return p;}

 execute(command,revision=this.revision,actor='user'){if(revision!==this.revision)fail('Stale revision: refresh before applying');if(!['user','model'].includes(actor))fail('Unknown actor');const candidate=clone(this.doc),patches=[];const write=(path,value)=>{let o=candidate;for(const k of path.slice(0,-1))o=o[k];const k=path.at(-1),before=clone(o[k]);if(canonical(before)===canonical(value))return;patches.push({path,before,after:clone(value)});o[k]=clone(value);};const idx=id=>{const i=candidate.clips.findIndex(c=>c.id===id);if(i<0)fail('Unknown clip');return i};
 let commandCount=0;const perform=(cmd,depth=0)=>{if(!cmd||typeof cmd!=='object'||depth>8||++commandCount>this.budgets.commands)fail('Command budget exceeded');if(cmd.type==='batch'){if(!Array.isArray(cmd.commands)||cmd.commands.length>this.budgets.commands)fail('Invalid batch');cmd.commands.forEach(child=>perform(child,depth+1));return;}if(cmd.type==='addClip'){write(['clips'],[...candidate.clips,this.make(cmd.template,cmd.start??0)]);return;}const i=idx(cmd.clip),c=candidate.clips[i];switch(cmd.type){
 case 'set':{const j=c.nodes.findIndex(n=>n.id===cmd.anchor);if(j<0)fail('Unknown anchor');validate(cmd.value,this.schema(c,c.nodes[j])[cmd.property]);write(['clips',i,'nodes',j,'props',cmd.property],cmd.value);break;}
 case 'keyframes':{const j=c.nodes.findIndex(n=>n.id===cmd.anchor);if(j<0)fail('Unknown anchor');write(['clips',i,'nodes',j,'keys'],{...c.nodes[j].keys,[cmd.property]:cmd.keys});break;}
 case 'addObject':{const n={id:cmd.id??'object.'+uid(),type:'overlay',overlay:true,label:cmd.label??'Caption card',props:{text:'A new idea',x:110,y:820,size:46,color:'#ffffff',background:'#183c41',opacity:1,visible:true,start:0,end:c.sourceDuration/HZ,style:'card',...cmd.props},keys:{}};write(['clips',i,'nodes'],[...c.nodes,n]);break;}
 case 'duplicateObject':{const n=this.node(c,cmd.anchor);if(!n.overlay)fail('Duplicate complete clips or added scene objects');const copy={...clone(n),id:cmd.id??'object.'+uid(),label:n.label+' copy'};copy.props.y=Math.min(1080,copy.props.y+70);write(['clips',i,'nodes'],[...c.nodes,copy]);break;}
 case 'deleteObject':{const n=this.node(c,cmd.anchor);if(!n.overlay)fail('Renderer anchors are required; use their visibility controls');write(['clips',i,'nodes'],c.nodes.filter(n=>n.id!==cmd.anchor));if(c.panel)write(['clips',i,'panel'],null);break;}
 case 'reorderObject':{const nodes=[...c.nodes],j=nodes.findIndex(n=>n.id===cmd.anchor);if(j<0||!nodes[j].overlay)fail('Only added objects can be reordered');const [n]=nodes.splice(j,1);nodes.splice(Math.max(0,Math.min(nodes.length,cmd.index)),0,n);write(['clips',i,'nodes'],nodes);break;}
 case 'duplicateClip':{const copy={...clone(c),id:uid(),name:c.name+' copy',start:c.start+c.duration};const clips=[...candidate.clips];clips.splice(i+1,0,copy);write(['clips'],clips);break;}
 case 'deleteClip':write(['clips'],candidate.clips.filter(x=>x.id!==c.id));break;
 case 'reorderClip':{const clips=clone(candidate.clips);clips.splice(i,1);clips.splice(Math.max(0,Math.min(clips.length,cmd.index)),0,clone(c));let at=0;for(const x of clips){x.start=at;at+=x.duration;}write(['clips'],clips);break;}
 case 'timing':{for(const k of ['start','duration','sourceIn','rate'])if(cmd[k]!==undefined)write(['clips',i,k],cmd[k]);break;}
 case 'split':{const left=cmd.at-c.start;if(left<=0||left>=c.duration)fail('Split must be inside clip');const right={...clone(c),id:uid(),start:cmd.at,duration:c.duration-left,sourceIn:c.sourceIn+Math.round(left*c.rate),name:c.name+' / continuation'};const clips=clone(candidate.clips);clips[i].duration=left;clips.splice(i+1,0,right);write(['clips'],clips);break;}
 case 'transform':write(['clips',i,'transform'],{...c.transform,...cmd.value});break;
 case 'panel':this.validatePanel(c,cmd.panel);write(['clips',i,'panel'],cmd.panel);break;
 case 'payload':if(this.templates[c.template].validatePayload)this.templates[c.template].validatePayload(cmd.payload);write(['clips',i,'payload'],cmd.payload);break;
 case 'html':if(c.template!=='html')fail('HTML command needs an HTML clip');write(['clips',i,'html'],cmd.html);break;
 default:fail('Unknown command');}};
 perform(command);this.check(candidate);if(!patches.length)return {noOp:true};const entry={id:uid(),actor,label:command.label??command.type,patches,time:new Date().toISOString()};entry.bytes=new TextEncoder().encode(JSON.stringify(entry)).length;if(entry.bytes>this.limit)fail('Edit exceeds history budget');this.history.length=this.cursor;this.history.push(entry);this.cursor++;this.doc=candidate;this.seq++;this.bytes=this.history.reduce((n,e)=>n+e.bytes,0);while(this.bytes>this.limit&&this.history.length){const e=this.history.shift();this.base=this.patch(this.base,e.patches,false);this.bytes-=e.bytes;this.cursor--;}return clone(entry);}
 patch(document,patches,inverse){const d=clone(document);for(const p of inverse?[...patches].reverse():patches){let o=d;for(const k of p.path.slice(0,-1)){if(typeof k==='string'&&!safe(k))fail('Unsafe patch');o=o[k];}const k=p.path.at(-1);if(typeof k==='string'&&!safe(k))fail('Unsafe patch');const expected=inverse?p.after:p.before;if(canonical(o[k])!==canonical(expected))fail('History before-state mismatch');o[k]=clone(inverse?p.before:p.after);}return this.check(d);}
 undo(){if(!this.canUndo)return;const next=this.patch(this.doc,this.history[this.cursor-1].patches,true);this.doc=next;this.cursor--;this.seq++;}
 redo(){if(!this.canRedo)return;const next=this.patch(this.doc,this.history[this.cursor].patches,false);this.doc=next;this.cursor++;this.seq++;}
 serialize(){return JSON.stringify({format:'scene-studio',version:1,binding:this.binding,base:this.base,history:this.history,cursor:this.cursor});}
 static restore(raw,templates,binding,options={}){if(typeof raw!=='string'||raw.length>32*1024*1024)fail('Project too large');const p=JSON.parse(raw);if(p.format!=='scene-studio'||p.version!==1||p.binding!==binding||!Array.isArray(p.history)||p.history.length>10000||!Number.isInteger(p.cursor)||p.cursor<0||p.cursor>p.history.length)fail('Incompatible project');const s=new Studio(templates,{...options,document:p.base,binding});for(const e of p.history){if(!Array.isArray(e.patches)||!e.patches.length)fail('Invalid history');s.doc=s.patch(s.doc,e.patches,false);}s.history=clone(p.history);s.cursor=p.history.length;s.bytes=s.history.reduce((a,e)=>a+new TextEncoder().encode(JSON.stringify(e)).length,0);while(s.cursor>p.cursor)s.undo();return s;}
}
export class FrameCache {constructor(limit=64*1024*1024){if(!Number.isFinite(limit)||limit<0)fail('Invalid cache budget');this.limit=limit;this.entries=new Map();this.bytes=0;this.hits=0;this.misses=0;}get(key){const x=this.entries.get(key);if(!x){this.misses++;return null;}this.entries.delete(key);this.entries.set(key,x);this.hits++;return x.value;}set(key,value,bytes){if(!Number.isFinite(bytes)||bytes<0)fail('Invalid cache size');if(this.entries.has(key))this.delete(key);if(bytes>this.limit)return false;while(this.bytes+bytes>this.limit)this.delete(this.entries.keys().next().value);this.entries.set(key,{value,bytes});this.bytes+=bytes;return true;}delete(key){const x=this.entries.get(key);if(x){x.value.close?.();this.bytes-=x.bytes;this.entries.delete(key);}}clear(){for(const key of this.entries.keys())this.delete(key);}}
export function sourceIdentity(c,time,binding){return canonical({binding,template:c.template,nodes:c.nodes.filter(n=>!n.overlay),html:c.html,payload:c.payload,time});}
